<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC78gYNU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC78gYNU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC78gYNU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC78gYNU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC78gYNU\App_KernelDevDebugContainer([
    'container.build_hash' => 'C78gYNU',
    'container.build_id' => 'ab919a81',
    'container.build_time' => 1710145019,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC78gYNU');
