<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG8YAVZc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG8YAVZc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG8YAVZc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG8YAVZc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG8YAVZc\App_KernelDevDebugContainer([
    'container.build_hash' => 'G8YAVZc',
    'container.build_id' => 'f2ddb89d',
    'container.build_time' => 1711966063,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG8YAVZc');
