<?php

namespace ContainerKwJrzjp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestRequestBodyDTOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\TestRequestBodyDTO' shared autowired service.
     *
     * @return \App\DTO\TestRequestBodyDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\DTO\\TestRequestBodyDTO": argument "$username" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
